# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-15 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loma', '0033_remove_daily_price_list_vendor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loma_master',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
