# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-26 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20190214_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='promocode_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocode_id', models.CharField(max_length=5)),
                ('promocode_name', models.CharField(max_length=11)),
                ('price', models.PositiveIntegerField()),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
